// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBAyDSKjDzmzTtAV_uFkhvjGIjl3XkDcc',
    appId: '1:165402352856:web:bf0ce5c93f5ac94f49cbad',
    messagingSenderId: '165402352856',
    projectId: 'moana-chat',
    authDomain: 'moana-chat.firebaseapp.com',
    storageBucket: 'moana-chat.appspot.com',
    measurementId: 'G-FXZ2EJHFNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY45g3orp-YZlvcd967j4MKy5iy61ykP0',
    appId: '1:165402352856:android:d204a293408a774e49cbad',
    messagingSenderId: '165402352856',
    projectId: 'moana-chat',
    storageBucket: 'moana-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyI5NcOhb_Q4AtkelDcEbKxmQq1DVZbYk',
    appId: '1:165402352856:ios:af1dbe88b48aec2349cbad',
    messagingSenderId: '165402352856',
    projectId: 'moana-chat',
    storageBucket: 'moana-chat.appspot.com',
    iosBundleId: 'com.example.moanaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyI5NcOhb_Q4AtkelDcEbKxmQq1DVZbYk',
    appId: '1:165402352856:ios:af1dbe88b48aec2349cbad',
    messagingSenderId: '165402352856',
    projectId: 'moana-chat',
    storageBucket: 'moana-chat.appspot.com',
    iosBundleId: 'com.example.moanaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBAyDSKjDzmzTtAV_uFkhvjGIjl3XkDcc',
    appId: '1:165402352856:web:5e1cbab88340bc9d49cbad',
    messagingSenderId: '165402352856',
    projectId: 'moana-chat',
    authDomain: 'moana-chat.firebaseapp.com',
    storageBucket: 'moana-chat.appspot.com',
    measurementId: 'G-5PLM6R51JX',
  );
}
